version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: api-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_USER: ${DB_USER}
    command: postgres -c max_connections=1000
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  redis:
    image: redis:8.0.2
    container_name: api-redis
    restart: always
    ports:
      - "${REDIS_CACHE_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data: 
  redis_data: